import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-blue-400">Next app starter template</h1>

        <p className="font-bold">Welcome to starter template</p>
      </main>
    </div>
  );
};

export default Home;
